Keyboard navigation and tiny css fix (center chevron)
etalab/covid19-dashboard pull request #175
Opened 2021-02-24 15:52 UTC by edouardlacroix

Small addon to allow navigation through dates using keyboard arrows !

2021-02-25 17:53 UTC, jdesboeufs requested changes

2021-02-25 17:53 UTC, jdesboeufs commented on components/date-nav.js
> +        console.log(previousDate)
Ce serait encore mieux sans les console.log :)

2021-02-25 17:53 UTC, jdesboeufs commented on components/date-nav.js
> +        console.log(nextDate)
Idem

2021-02-25 17:53 UTC, jdesboeufs commented on components/date-nav.js
> +    window.addEventListener('keydown', handleKeyDown)
Encapsuler dans un `if (process.browser)` car `window` n'existe pas en environnement SSR.

2021-02-25 20:31 UTC, jdesboeufs commented
Merci pour cette contribution !
J'en profite pour signaler qu'il est désormais possible de faire tourne tous les traitements sans habilitation particulière.

2021-02-26 08:19 UTC, edouardlacroix commented
Modifications faites. Merci pour le retour 😀 !

2021-02-26 08:27 UTC, edouardlacroix commented
Je viens de lire que process.browser est deprecated ( [https://github.com/vercel/next.js/pull/7651] )
Je l'ai donc remplacé par typeOf window !== 'undefined' ([https://github.com/vercel/next.js/issues/5354])

2021-02-26 10:48 UTC, jdesboeufs commented
On aura appris quelque chose alors 😅
@tmerlier ça va t'intéresser.

2021-02-26 10:52 UTC, jdesboeufs approved these changes

2021-02-26 10:52 UTC, merged